version: '1.0.0.{build}'
branches:
  only:
    - master

image: Visual Studio 2015
clone_depth: 1
environment:
  global:
    LatestLTSQtVersion: 5.9
  matrix:
  - QT5: C:\Qt\5.11\msvc2015_64
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    platform: amd64
    use_mingw: "false"
  - QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    platform: x86
    use_mingw: "false"
  - QT5: C:\Qt\%LatestLTSQtVersion%\mingw53_32
    COMPILER: C:\Qt\Tools\mingw530_32
    platform: x86
    use_mingw: "true"

matrix:
  fast_finish: true

before_build:
- set PATH=%COMPILER%\bin;%QT5%\bin;%PATH%
- if not %use_mingw%==true call "%COMPILER%\vcvarsall.bat" %platform%
- if %use_mingw%==true (set CMAKEGENERATOR="MinGW Makefiles") else (set CMAKEGENERATOR="NMake Makefiles")
- if %use_mingw%==true set PATH=%PATH:C:\Program Files\Git\usr\bin;=%

build_script:
- echo Extra CMake Modules
- '"%programfiles%\Git\usr\bin\git.exe" clone git://anongit.kde.org/extra-cmake-modules ECM'
- cd ECM
- mkdir .\build 
- cd .\build
- cmake -G %CMAKEGENERATOR% -DCMAKE_INSTALL_PREFIX=../../ECMbuild -DCMAKE_BUILD_TYPE=RELEASE ../
- cmake --build .
- cmake --build . --target install
- cd ..\..\
- echo KItemModels
- '"%programfiles%\Git\usr\bin\git.exe" clone git://anongit.kde.org/kitemmodels.git KItemModels'
- cd KItemModels
- mkdir .\build 
- cd .\build
- cmake -G %CMAKEGENERATOR% -DCMAKE_DEBUG_POSTFIX=d -DCMAKE_INSTALL_PREFIX=../../KDEdeploy -DCMAKE_BUILD_TYPE=DEBUG ../
- cmake --build .
- cmake --build . --target install
- cmake -G %CMAKEGENERATOR% -DCMAKE_INSTALL_PREFIX=../../KDEdeploy -DCMAKE_BUILD_TYPE=RELEASE ../
- cmake --build .
- cmake --build . --target install
- cd ..\..\

after_build:
- if %use_mingw%==true set PATH=C:\Program Files\Git\usr\bin;%PATH%
- if %use_mingw%==true (set archivename=mingw) else (set archivename=msvc2015)
- if %platform%==x86 (set archivename=%archivename%_x86) else (set archivename=%archivename%_x64)
- 7z a -tzip KDEapi.zip .\KDEdeploy\*

artifacts:
- path: '.\KDEapi.zip'