version: '1.0.0.{build}'
branches:
  only:
    - master

image: Visual Studio 2015
clone_depth: 1
environment:
  global:
    LatestLTSQtVersion: 5.9
  matrix:
  - NAME: KArchiveMSVC2015x64
    module_name: KArchive
    module_repo: karchive.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015_64
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    platform: amd64
    use_mingw: "false"
    python_path: C:\Python37-x64
  - NAME: KArchiveMSVC2015x32
    module_name: KArchive
    module_repo: karchive.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    platform: x86
    use_mingw: "false"
    python_path: C:\Python37
  - NAME: KArchiveMinGWx32
    module_name: KArchive
    module_repo: karchive.git
    QT5: C:\Qt\%LatestLTSQtVersion%\mingw53_32
    COMPILER: C:\Qt\Tools\mingw530_32
    platform: x86
    use_mingw: "true"
    python_path: C:\Python37
  - NAME: KCodecsMSVC2015x64
    module_name: KCodecs
    module_repo: kcodecs.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015_64
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    platform: amd64
    use_mingw: "false"
    python_path: C:\Python37-x64
  - NAME: KCodecsMSVC2015x32
    module_name: KCodecs
    module_repo: kcodecs.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    platform: x86
    use_mingw: "false"
    python_path: C:\Python37
  - NAME: KCodecsMinGWx32
    module_name: KCodecs
    module_repo: kcodecs.git
    QT5: C:\Qt\%LatestLTSQtVersion%\mingw53_32
    COMPILER: C:\Qt\Tools\mingw530_32
    platform: x86
    use_mingw: "true"
    python_path: C:\Python37
  - NAME: KItemModelsMSVC2015x64
    module_name: KItemModels
    module_repo: kitemmodels.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015_64
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    platform: amd64
    use_mingw: "false"
    python_path: C:\Python37-x64
  - NAME: KItemModelsMSVC2015x32
    module_name: KItemModels
    module_repo: kitemmodels.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    platform: x86
    use_mingw: "false"
    python_path: C:\Python37
  - NAME: KItemModelsMinGWx32
    module_name: KItemModels
    module_repo: kitemmodels.git
    QT5: C:\Qt\%LatestLTSQtVersion%\mingw53_32
    COMPILER: C:\Qt\Tools\mingw530_32
    platform: x86
    use_mingw: "true"
    python_path: C:\Python37
  - NAME: KItemViewsMSVC2015x64
    module_name: KItemViews
    module_repo: kitemviews.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015_64
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    platform: amd64
    use_mingw: "false"
    python_path: C:\Python37-x64
  - NAME: KItemViewsMSVC2015x32
    module_name: KItemViews
    module_repo: kitemviews.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    platform: x86
    use_mingw: "false"
    python_path: C:\Python37
  - NAME: KItemViewsMinGWx32
    module_name: KItemViews
    module_repo: kitemviews.git
    QT5: C:\Qt\%LatestLTSQtVersion%\mingw53_32
    COMPILER: C:\Qt\Tools\mingw530_32
    platform: x86
    use_mingw: "true"
    python_path: C:\Python37
  - NAME: KCoreAddonsMSVC2015x64
    module_name: KCoreAddons
    module_repo: kcoreaddons.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015_64
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    platform: amd64
    use_mingw: "false"
    python_path: C:\Python37-x64
  - NAME: KCoreAddonsMSVC2015x32
    module_name: KCoreAddons
    module_repo: kcoreaddons.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    platform: x86
    use_mingw: "false"
    python_path: C:\Python37
  - NAME: KCoreAddonsMinGWx32
    module_name: KCoreAddons
    module_repo: kcoreaddons.git
    QT5: C:\Qt\%LatestLTSQtVersion%\mingw53_32
    COMPILER: C:\Qt\Tools\mingw530_32
    platform: x86
    use_mingw: "true"
    python_path: C:\Python37
  - NAME: KGuiAddonsMSVC2015x64
    module_name: KGuiAddons
    module_repo: kguiaddons.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015_64
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    platform: amd64
    use_mingw: "false"
    python_path: C:\Python37-x64
  - NAME: KGuiAddonsMSVC2015x32
    module_name: KGuiAddons
    module_repo: kguiaddons.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    platform: x86
    use_mingw: "false"
    python_path: C:\Python37
  - NAME: KGuiAddonsMinGWx32
    module_name: KGuiAddons
    module_repo: kguiaddons.git
    QT5: C:\Qt\%LatestLTSQtVersion%\mingw53_32
    COMPILER: C:\Qt\Tools\mingw530_32
    platform: x86
    use_mingw: "true"
    python_path: C:\Python37
  - NAME: KWidgetsAddonsMSVC2015x64
    module_name: KWidgetsAddons
    module_repo: kwidgetsaddons.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015_64
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    platform: amd64
    use_mingw: "false"
    python_path: C:\Python37-x64
  - NAME: KWidgetsAddonsMSVC2015x32
    module_name: KWidgetsAddons
    module_repo: kwidgetsaddons.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    platform: x86
    use_mingw: "false"
    python_path: C:\Python37
  - NAME: KWidgetsAddonsMinGWx32
    module_name: KWidgetsAddons
    module_repo: kwidgetsaddons.git
    QT5: C:\Qt\%LatestLTSQtVersion%\mingw53_32
    COMPILER: C:\Qt\Tools\mingw530_32
    platform: x86
    use_mingw: "true"
    python_path: C:\Python37
  - NAME: KIdleTimeMSVC2015x64
    module_name: KIdleTime
    module_repo: kidletime.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015_64
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    platform: amd64
    use_mingw: "false"
    python_path: C:\Python37-x64
  - NAME: KIdleTimeMSVC2015x32
    module_name: KIdleTime
    module_repo: kidletime.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    platform: x86
    use_mingw: "false"
    python_path: C:\Python37
  - NAME: KIdleTimeMinGWx32
    module_name: KIdleTime
    module_repo: kidletime.git
    QT5: C:\Qt\%LatestLTSQtVersion%\mingw53_32
    COMPILER: C:\Qt\Tools\mingw530_32
    platform: x86
    use_mingw: "true"
    python_path: C:\Python37

matrix:
  fast_finish: true

before_build:
- set PATH=%COMPILER%\bin;%QT5%\bin;%python_path%;%PATH%
- if not %use_mingw%==true call "%COMPILER%\vcvarsall.bat" %platform%
- if %use_mingw%==true (set CMAKEGENERATOR="MinGW Makefiles") else (set CMAKEGENERATOR="NMake Makefiles")
- if %use_mingw%==true set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
- if %module_name%==KCodecs mkdir .\gperf
- if %module_name%==KCodecs cd .\gperf
- if %module_name%==KCodecs curl -k -L https://sourceforge.net/projects/gnuwin32/files/gperf/3.0.1/gperf-3.0.1-bin.zip --output gperf.zip
- if %module_name%==KCodecs 7z x gperf.zip
- if %module_name%==KCodecs set PATH=%CD%\bin;%PATH%
- if %module_name%==KArchive mkdir .\bzip2
- if %module_name%==KArchive cd .\bzip2
- if %module_name%==KArchive curl -k -L https://sourceforge.net/projects/gnuwin32/files/bzip2/1.0.5/bzip2-1.0.5-bin.zip --output bzip2.zip
- if %module_name%==KArchive 7z x bzip2.zip
- if %module_name%==KArchive dir
- if %module_name%==KArchive set PATH=%CD%;%PATH%
- if %module_name%==KArchive cd ..\
- if %module_name%==KArchive mkdir .\liblzma
- if %module_name%==KArchive cd .\liblzma
- if %module_name%==KArchive curl -k -L https://tukaani.org/xz/xz-5.2.4.tar.gz --output liblzma.zip
- if %module_name%==KArchive 7z x liblzma.zip
- if %module_name%==KArchive dir liblzma
- if %module_name%==KArchive set PATH=%CD%\liblzma;%PATH%
- if %module_name%==KArchive cd ..\
- git clone git://anongit.kde.org/extra-cmake-modules ECM
- cd ECM
- mkdir .\build 
- cd .\build
- cmake -G %CMAKEGENERATOR% -DCMAKE_INSTALL_PREFIX=../../ECMbuild -DCMAKE_BUILD_TYPE=RELEASE ../
- cmake --build .
- cmake --build . --target install
- cd ..\..\
- set PATH=%CD%\ECMbuild;%PATH%
- git clone https://github.com/madler/zlib.git zlibBuild
- cd zlibBuild
- mkdir .\build 
- cd .\build
- cmake -G %CMAKEGENERATOR% -DCMAKE_DEBUG_POSTFIX=d -DCMAKE_INSTALL_PREFIX=../../zlib -DCMAKE_BUILD_TYPE=DEBUG ../
- cmake --build .
- cmake --build . --target install
- cmake -G %CMAKEGENERATOR% -DCMAKE_INSTALL_PREFIX=../../zlib -DCMAKE_BUILD_TYPE=RELEASE ../
- cmake --build .
- cmake --build . --target install
- cd ..\..\
- set PATH=%CD%\zlib;%PATH%

build_script:
- echo KCodecs
- git clone git://anongit.kde.org/%module_repo% %module_name%
- cd %module_name%
- mkdir .\build 
- cd .\build
- cmake -G %CMAKEGENERATOR% -DCMAKE_DEBUG_POSTFIX=d -DCMAKE_INSTALL_PREFIX=../../KDEdeploy -DCMAKE_BUILD_TYPE=DEBUG ../
- cmake --build .
- cmake --build . --target install
- cmake -G %CMAKEGENERATOR% -DCMAKE_INSTALL_PREFIX=../../KDEdeploy -DCMAKE_BUILD_TYPE=RELEASE ../
- cmake --build .
- cmake --build . --target install
- cd ..\..\

after_build:
- if %use_mingw%==true set PATH=C:\Program Files\Git\usr\bin;%PATH%
- if %use_mingw%==true (set archivename=mingw) else (set archivename=msvc2015)
- if %platform%==x86 (set archivename=%archivename%_x86) else (set archivename=%archivename%_x64)
- 7z a -tzip %module_name%.zip .\KDEdeploy\*

artifacts:
- path: '.\*.zip'