version: '1.0.0.{build}'
branches:
  only:
    - master

image: Visual Studio 2015
clone_depth: 1
environment:
  global:
    LatestLTSQtVersion: 5.9
    boost_path: C:\Libraries\boost_1_67_0
  matrix:
  - NAME: KArchiveMSVC2015x64
    module_name: KArchive
    module_repo: karchive.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015_64
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    comp_platform: amd64
    use_mingw: "false"
    python_path: C:\Python37-x64
  - NAME: KArchiveMSVC2015x32
    module_name: KArchive
    module_repo: karchive.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    comp_platform: x86
    use_mingw: "false"
    python_path: C:\Python37
  - NAME: KArchiveMinGWx32
    module_name: KArchive
    module_repo: karchive.git
    QT5: C:\Qt\%LatestLTSQtVersion%\mingw53_32
    COMPILER: C:\Qt\Tools\mingw530_32
    comp_platform: x86
    use_mingw: "true"
    python_path: C:\Python37
  - NAME: KCodecsMSVC2015x64
    module_name: KCodecs
    module_repo: kcodecs.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015_64
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    comp_platform: amd64
    use_mingw: "false"
    python_path: C:\Python37-x64
  - NAME: KCodecsMSVC2015x32
    module_name: KCodecs
    module_repo: kcodecs.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    comp_platform: x86
    use_mingw: "false"
    python_path: C:\Python37
  - NAME: KCodecsMinGWx32
    module_name: KCodecs
    module_repo: kcodecs.git
    QT5: C:\Qt\%LatestLTSQtVersion%\mingw53_32
    COMPILER: C:\Qt\Tools\mingw530_32
    comp_platform: x86
    use_mingw: "true"
    python_path: C:\Python37
  - NAME: KItemModelsMSVC2015x64
    module_name: KItemModels
    module_repo: kitemmodels.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015_64
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    comp_platform: amd64
    use_mingw: "false"
    python_path: C:\Python37-x64
  - NAME: KItemModelsMSVC2015x32
    module_name: KItemModels
    module_repo: kitemmodels.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    comp_platform: x86
    use_mingw: "false"
    python_path: C:\Python37
  - NAME: KItemModelsMinGWx32
    module_name: KItemModels
    module_repo: kitemmodels.git
    QT5: C:\Qt\%LatestLTSQtVersion%\mingw53_32
    COMPILER: C:\Qt\Tools\mingw530_32
    comp_platform: x86
    use_mingw: "true"
    python_path: C:\Python37
  - NAME: KItemViewsMSVC2015x64
    module_name: KItemViews
    module_repo: kitemviews.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015_64
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    comp_platform: amd64
    use_mingw: "false"
    python_path: C:\Python37-x64
  - NAME: KItemViewsMSVC2015x32
    module_name: KItemViews
    module_repo: kitemviews.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    comp_platform: x86
    use_mingw: "false"
    python_path: C:\Python37
  - NAME: KItemViewsMinGWx32
    module_name: KItemViews
    module_repo: kitemviews.git
    QT5: C:\Qt\%LatestLTSQtVersion%\mingw53_32
    COMPILER: C:\Qt\Tools\mingw530_32
    comp_platform: x86
    use_mingw: "true"
    python_path: C:\Python37
  - NAME: KCoreAddonsMSVC2015x64
    module_name: KCoreAddons
    module_repo: kcoreaddons.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015_64
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    comp_platform: amd64
    use_mingw: "false"
    python_path: C:\Python37-x64
  - NAME: KCoreAddonsMSVC2015x32
    module_name: KCoreAddons
    module_repo: kcoreaddons.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    comp_platform: x86
    use_mingw: "false"
    python_path: C:\Python37
  - NAME: KCoreAddonsMinGWx32
    module_name: KCoreAddons
    module_repo: kcoreaddons.git
    QT5: C:\Qt\%LatestLTSQtVersion%\mingw53_32
    COMPILER: C:\Qt\Tools\mingw530_32
    comp_platform: x86
    use_mingw: "true"
    python_path: C:\Python37
  - NAME: KGuiAddonsMSVC2015x64
    module_name: KGuiAddons
    module_repo: kguiaddons.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015_64
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    comp_platform: amd64
    use_mingw: "false"
    python_path: C:\Python37-x64
  - NAME: KGuiAddonsMSVC2015x32
    module_name: KGuiAddons
    module_repo: kguiaddons.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    comp_platform: x86
    use_mingw: "false"
    python_path: C:\Python37
  - NAME: KGuiAddonsMinGWx32
    module_name: KGuiAddons
    module_repo: kguiaddons.git
    QT5: C:\Qt\%LatestLTSQtVersion%\mingw53_32
    COMPILER: C:\Qt\Tools\mingw530_32
    comp_platform: x86
    use_mingw: "true"
    python_path: C:\Python37
  - NAME: KWidgetsAddonsMSVC2015x64
    module_name: KWidgetsAddons
    module_repo: kwidgetsaddons.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015_64
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    comp_platform: amd64
    use_mingw: "false"
    python_path: C:\Python37-x64
  - NAME: KWidgetsAddonsMSVC2015x32
    module_name: KWidgetsAddons
    module_repo: kwidgetsaddons.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    comp_platform: x86
    use_mingw: "false"
    python_path: C:\Python37
  - NAME: KWidgetsAddonsMinGWx32
    module_name: KWidgetsAddons
    module_repo: kwidgetsaddons.git
    QT5: C:\Qt\%LatestLTSQtVersion%\mingw53_32
    COMPILER: C:\Qt\Tools\mingw530_32
    comp_platform: x86
    use_mingw: "true"
    python_path: C:\Python37
  - NAME: KIdleTimeMSVC2015x64
    module_name: KIdleTime
    module_repo: kidletime.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015_64
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    comp_platform: amd64
    use_mingw: "false"
    python_path: C:\Python37-x64
  - NAME: KIdleTimeMSVC2015x32
    module_name: KIdleTime
    module_repo: kidletime.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    comp_platform: x86
    use_mingw: "false"
    python_path: C:\Python37
  - NAME: KIdleTimeMinGWx32
    module_name: KIdleTime
    module_repo: kidletime.git
    QT5: C:\Qt\%LatestLTSQtVersion%\mingw53_32
    COMPILER: C:\Qt\Tools\mingw530_32
    comp_platform: x86
    use_mingw: "true"
    python_path: C:\Python37
  - NAME: KImageFormatsMSVC2015x64
    module_name: KImageFormats
    module_repo: kimageformats.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015_64
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    comp_platform: amd64
    use_mingw: "false"
    python_path: C:\Python37-x64
  - NAME: KImageFormatsMSVC2015x32
    module_name: KImageFormats
    module_repo: kimageformats.git
    QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    comp_platform: x86
    use_mingw: "false"
    python_path: C:\Python37
  - NAME: KImageFormatsMinGWx32
    module_name: KImageFormats
    module_repo: kimageformats.git
    QT5: C:\Qt\%LatestLTSQtVersion%\mingw53_32
    COMPILER: C:\Qt\Tools\mingw530_32
    comp_platform: x86
    use_mingw: "true"
    python_path: C:\Python37

matrix:
  fast_finish: true

before_build:
- set need_OpenEXR=false
- if %module_name%==KImageFormats set need_OpenEXR=true
- set need_gperf=false
- if %module_name%==KCodecs set need_gperf=true
- set need_bzip2=false
- if %module_name%==KArchive set need_bzip2=true
- if %use_mingw%==true set need_bzip2=false
- set need_zlib=false
- if %module_name%==KArchive set need_zlib=true
- if %need_OpenEXR%==true set need_zlib=true
- set need_liblzma=false
- if %module_name%==KArchive set need_liblzma=true
- set PATH=%boost_path%;%python_path%;%python_path%\Scripts%PATH%
- python -m pip install -U pip
- pip install -U Sphinx
- set originalWD=%CD%
- call "%QT5%\bin\qtenv2.bat"
- cd %originalWD%
- echo on
- if not %use_mingw%==true call "%COMPILER%\vcvarsall.bat" %comp_platform%
- if %use_mingw%==true (set CMAKEGENERATOR="MinGW Makefiles") else (set CMAKEGENERATOR="NMake Makefiles")
- if %use_mingw%==true set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
- if %need_gperf%==true mkdir .\gperf && cd .\gperf
- if %need_gperf%==true curl -k -L https://sourceforge.net/projects/gnuwin32/files/gperf/3.0.1/gperf-3.0.1-bin.zip --output gperf.zip
- if %need_gperf%==true 7z x gperf.zip
- if %need_gperf%==true move /Y gperf.zip ..\
- if %need_gperf%==true set PATH=%CD%\bin;%PATH%
- if %need_gperf%==true cd ..\
- if %need_bzip2%==true mkdir .\bzip2src && cd .\bzip2src
- if %need_bzip2%==true curl -k -L https://sourceforge.net/projects/gnuwin32/files/bzip2/1.0.5/bzip2-1.0.5-src.zip --output bzip2.zip
- if %need_bzip2%==true 7z x bzip2.zip
- if %need_bzip2%==true del /F /Q  bzip2.zip
- if %need_bzip2%==true cd src\bzip2\1.0.5\bzip2-1.0.5\
- if %need_bzip2%==true copy /Y %originalWD%\bzip2CMakeLists.txt CMakeLists.txt
- if %need_bzip2%==true mkdir build && cd build
- if %need_bzip2%==true cmake -G %CMAKEGENERATOR% -DCMAKE_INSTALL_PREFIX=../../../../../../bzip2 -DCMAKE_BUILD_TYPE=RELEASE ../
- if %need_bzip2%==true cmake --build .
- if %need_bzip2%==true cmake --build . --target install
- if %need_bzip2%==true cd ..\..\..\..\..\..\
- if %need_bzip2%==true set PATH=%CD%\bzip2;%PATH%
- if %need_bzip2%==true 7z a -tzip bzip2.zip .\bzip2\*
- if %need_liblzma%==true mkdir .\liblzma && cd .\liblzma
- if %need_liblzma%==true curl -k -L https://tukaani.org/xz/xz-5.2.4-windows.zip --output liblzma.zip
- if %need_liblzma%==true 7z x liblzma.zip
- if %need_liblzma%==true del /F /Q liblzma.zip
- if %need_liblzma%==true if %use_mingw%==true (ren bin_i686 lib) else (mkdir lib && mkdir bin)
- if %need_liblzma%==true if %use_mingw%==false curl -k -L https://tukaani.org/xz/xz-5.2.4.tar.gz --output liblzma.tar.gz
- if %need_liblzma%==true if %use_mingw%==false 7z x liblzma.tar.gz
- if %need_liblzma%==true if %use_mingw%==false del /F /Q liblzma.tar.gz
- if %need_liblzma%==true if %use_mingw%==false 7z x liblzma.tar
- if %need_liblzma%==true if %use_mingw%==false del /F /Q liblzma.tar
- if %need_liblzma%==true if %use_mingw%==false cd xz-5.2.4\windows\vs2013
- if %need_liblzma%==true if %comp_platform%==x86 if %use_mingw%==false msbuild xz_win.sln /property:Configuration=Release /property:Platform=Win32 && xcopy /Y /I /K Release\Win32\liblzma_dll\*.dll ..\..\..\bin && xcopy /Y /I /K Release\Win32\liblzma_dll\*.lib ..\..\..\lib
- if %need_liblzma%==true if %comp_platform%==amd64 if %use_mingw%==false msbuild xz_win.sln /property:Configuration=Release /property:Platform=x64 && xcopy /Y /I /K Release\x64\liblzma_dll\*.dll ..\..\..\bin && xcopy /Y /I /K Release\x64\liblzma_dll\*.lib ..\..\..\lib
- if %need_liblzma%==true if %use_mingw%==false cd ..\..\..\
- if %need_liblzma%==true set PATH=%CD%;%PATH%
- if %need_liblzma%==true cd ..\
- if %need_liblzma%==true 7z a -tzip liblzma.zip .\liblzma\include\
- if %need_liblzma%==true 7z a -tzip liblzma.zip .\liblzma\lib\
- if %need_liblzma%==true if %use_mingw%==false 7z a -tzip liblzma.zip .\liblzma\bin\
- if %need_zlib%==true git clone https://github.com/madler/zlib.git zlibBuild
- if %need_zlib%==true cd zlibBuild
- if %need_zlib%==true mkdir .\build && cd .\build
- if %need_zlib%==true cmake -G %CMAKEGENERATOR% -DCMAKE_INSTALL_PREFIX=../../zlib -DCMAKE_BUILD_TYPE=RELEASE ../
- if %need_zlib%==true cmake --build .
- if %need_zlib%==true cmake --build . --target install
- if %need_zlib%==true cd ..\..\
- if %need_zlib%==true 7z a -tzip zlib.zip .\zlib\*
- if %need_zlib%==true set PATH=%CD%\zlib;%PATH%
- if %need_OpenEXR%==true git clone https://github.com/openexr/openexr.git OpenEXRsrc
- if %need_OpenEXR%==true cd OpenEXRsrc
- if %need_OpenEXR%==true mkdir .\build && cd .\build
- if %need_OpenEXR%==true cmake -G %CMAKEGENERATOR% -DOPENEXR_BUILD_PYTHON_LIBS=OFF -DOPENEXR_ENABLE_TESTS=OFF -DCMAKE_INSTALL_PREFIX=../../OpenEXR -DCMAKE_BUILD_TYPE=RELEASE ../
- if %need_OpenEXR%==true cmake --build .
- if %need_OpenEXR%==true cmake --build . --target install
- if %need_OpenEXR%==true cd ..\..\
- if %need_OpenEXR%==true 7z a -tzip OpenEXR.zip .\OpenEXR\*
- if %need_OpenEXR%==true set PATH=%CD%\OpenEXR;%PATH%
- git clone git://anongit.kde.org/extra-cmake-modules ECM
- cd ECM
- mkdir .\build 
- cd .\build
- cmake -G %CMAKEGENERATOR% -DBUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX=../../ECMbuild -DCMAKE_BUILD_TYPE=RELEASE ../
- cmake --build .
- cmake --build . --target install
- cd ..\..\
- set PATH=%CD%\ECMbuild;%PATH%

build_script:
- git clone git://anongit.kde.org/%module_repo% %module_name%
- cd %module_name%
- mkdir .\build 
- cd .\build
- cmake -G %CMAKEGENERATOR% -DBUILD_TESTING=OFF -DCMAKE_DEBUG_POSTFIX=d -DCMAKE_INSTALL_PREFIX=../../KDEAPI -DCMAKE_BUILD_TYPE=DEBUG ../
- cmake --build .
- cmake --build . --target install
- cmake -G %CMAKEGENERATOR% -DBUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX=../../KDEAPI -DCMAKE_BUILD_TYPE=RELEASE ../
- cmake --build .
- cmake --build . --target install
- cd ..\..\

after_build:
- if %use_mingw%==true set PATH=C:\Program Files\Git\usr\bin;%PATH%
- if %use_mingw%==true (set archivename=mingw) else (set archivename=msvc2015)
- if %comp_platform%==x86 (set archivename=%archivename%_x86) else (set archivename=%archivename%_x64)
- 7z a -tzip %module_name%.zip .\KDEAPI\*

artifacts:
- path: '.\*.zip'