version: '1.0.0.{build}'
branches:
  only:
    - master

image: Visual Studio 2015
clone_depth: 1
environment:
  global:
    LatestLTSQtVersion: 5.9
  matrix:
  - QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015_64
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    comp_platform: amd64
matrix:
  fast_finish: true

before_build:
- set originalWD=%CD%
- call "%QT5%\bin\qtenv2.bat"
- cd %originalWD%
- echo on
- call "%COMPILER%\vcvarsall.bat" %comp_platform%
- set CMAKEGENERATOR="NMake Makefiles"
- mkdir bzip2 && cd bzip2
- mkdir bin && mkdir lib && mkdir include
- git clone https://git.code.sf.net/p/bzip2/bzip2 sources
- cd sources
- devenv /upgrade libbz2.dsp
- devenv libbz2.vcxproj /build Release
- xcopy /Y /I /K *.dll ..\bin
- xcopy /Y /I /K bzlib.h ..\include
- xcopy /Y /I /K Release\*.lib ..\lib
- xcopy /Y /I /K Release\*.a ..\lib
- xcopy /Y /I /K Release\*.o ..\lib
- cd ..\
- rmdir sources /S /Q
- set PATH=%CD%;%PATH%
- cd ..\
- git clone https://github.com/madler/zlib.git zlibBuild
- cd zlibBuild
- mkdir .\build 
- cd .\build
- cmake -G %CMAKEGENERATOR% -DCMAKE_DEBUG_POSTFIX=d -DCMAKE_INSTALL_PREFIX=../../zlib -DCMAKE_BUILD_TYPE=DEBUG ../
- cmake --build .
- cmake --build . --target install
- cmake -G %CMAKEGENERATOR% -DCMAKE_INSTALL_PREFIX=../../zlib -DCMAKE_BUILD_TYPE=RELEASE ../
- cmake --build .
- cmake --build . --target install
- cd ..\..\
- set PATH=%CD%\zlib;%PATH%
- git clone git://anongit.kde.org/extra-cmake-modules ECM
- cd ECM
- mkdir .\build 
- cd .\build
- cmake -G %CMAKEGENERATOR% -DBUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX=../../ECMbuild -DCMAKE_BUILD_TYPE=RELEASE ../
- cmake --build .
- cmake --build . --target install
- cd ..\..\
- set PATH=%CD%\ECMbuild;%PATH%

build_script:
- git clone git://anongit.kde.org/karchive.git KArchive
- cd KArchive
- mkdir .\build 
- cd .\build
- cmake -G %CMAKEGENERATOR% -DCMAKE_DEBUG_POSTFIX=d -DCMAKE_INSTALL_PREFIX=../../KDEAPI -DCMAKE_BUILD_TYPE=DEBUG ../
- cmake --build .
- cmake --build . --target install
- cmake -G %CMAKEGENERATOR% -DCMAKE_INSTALL_PREFIX=../../KDEAPI -DCMAKE_BUILD_TYPE=RELEASE ../
- cmake --build .
- cmake --build . --target install
- cd ..\..\
